services:
  - type: web
    name: pantry-builder
    env: node
    buildCommand: npm install && npm install --prefix client && npm install --prefix server && npm run build
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
